[package]
name = "mips-circuits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
plonky2 = { git = "https://github.com/0xPolygonZero/plonky2", branch = "main", features = ["timing"] }
starky = { git = "https://github.com/0xPolygonZero/plonky2", branch = "main" , features = ["timing"] }
plonky2_evm = { git = "https://github.com/0xPolygonZero/plonky2", branch = "main" }
plonky2_util = { git = "https://github.com/0xPolygonZero/plonky2", branch = "main" }
itertools = "0.11.0"
log = { version = "0.4.14", default-features = false }
anyhow = { version = "1.0.40", default-features = false }

[dev-dependencies]
env_logger = { version = "0.9.0", default-features = false }
